CREATE TABLE CGV(
	CID INT PRIMARY KEY, -- 기본키
	TITLE VARCHAR(100) NOT NULL, -- 영화제목
	IMAGE VARCHAR(1000) NOT NULL, -- 영화포스터 URL
	GENRE VARCHAR(100),-- 장르
	BOOKCNT INT DEFAULT 0 -- 예매한 횟수
);

CREATE TABLE MEMBER(
	MID VARCHAR(20) PRIMARY KEY, -- 아이디
	MPW VARCHAR(100) NOT NULL, -- 비밀번호
	MNAME VARCHAR(50) NOT NULL, -- 사용자이름
	MBOOK VARCHAR(2000) -- 최근 예매한 영화
);

CREATE TABLE BOOK(
   BID INT PRIMARY KEY, -- 기본키
   CID INT, -- CGV 외래키
   MID VARCHAR(20) -- MEMBER 외래키
);
	
DROP TABLE BOOK;
	
	